ni-kismet/engineering-flot

examples/ajax/index.html
examples/annotating/index.html
examples/axes-interacting/index.html
examples/axes-time-zones/index.html
examples/axes-time/index.html
examples/basic-options/index.html
examples/basic-usage/index.html
examples/canvas/index.html
examples/categories/index.html
examples/cursors/index.html
examples/image/index.html
examples/index.html
examples/interacting/index.html
examples/log-scale/index.html
examples/percentiles/index.html
examples/realtime/index.html
examples/resize/index.html
examples/selection/index.html
examples/series-errorbars/index.html
examples/series-pie/index.html
examples/series-toggle/index.html
examples/series-types/index.html
examples/stacking/index.html
examples/symbols/index.html
examples/threshold/index.html
examples/tracking/index.html
examples/visitors/index.html
examples/zooming/index.html

(1) The missing log-scales and cursors examples were added to the main index.html file.
(2) These examples are still failing:
examples/axes-time/index.html
examples/visitors/index.html
examples/axes-time-zones/index.html
examples/axes-multiple/index.html
examples/canvas/index.html
because the axes have to write the time and by default there is no tickGenerator (anymore) that can handle the time.
(3) By default the grid is not drawn anymore. Each set of vertical or horizontal set of lines have to be requested in the options for each series when the graph is created. See this example that was previously updated: https://github.com/cipix2000/engineering-flot/blob/master/examples/interacting/index.html

Fixing the examples

---

README.md

The badge is now pointing to this: https://coveralls.io/github/ni-kismet/engineering-flot

Updating coveralls badge

---

dist/jquery.flot.js
jquery.flot.js
jquery.flot.logaxis.js
tests/jquery.flot-precision.Test.js
tests/jquery.flot.logaxis.Test.js

The quick fix that was made before could mess with the precision formula for axis that uses SI notation

Rehandled check for negative precision in logAxis formatter

---

jquery.flot.navigate.js
tests/jquery.flot.navigate-interaction.Test.js
tests/utils/simulate.js

The event listener for reCenter is defined in ni-graph-tools, so i cannot properly test it from engineering-flot....

Bind dblclick event for zoom. Add support for test

---

API.md
dist/jquery.flot.js
jquery.flot.axislabels.js
jquery.flot.js
tests/jquery.flot.axislabels.Test.js

In order to improve the speed of the drawing of the axis labels, the AxisLabels plug is now refactored to take advantage of the caching mechanism of the CanvasWrapper plugin.
Performance before:
Performance after:
Each axis label has it's own div translated and rotated. I think that eventually the CanvasWrapper plugin will be able to rotate the text by itself.
For a graph like this...
This is the corresponding div soup:

Cache axis labels

---

dist/jquery.flot.js
jquery.flot.js
tests/jquery.flot.Test.js

If x axis label width is big, the plotOffset.left will be changed based on it. This can cause the drawing of y axis not close to the plot. To fix this, the y axis box.left will be increased with the same amount as plotOffset.left.
The same problem can appear on any combination of axis with axis position after updating plotOffset.

Adjust y axis box.left so that the axis will be next to the plot

---

jquery.flot.axislabels.js
tests/jquery.flot.axislabels.Test.js

For colorScale if axis label was not visible, the extra 20 space was not reserved.

Reserve space specified by axis.boxPosition even is axisLabel not visible

---

dist/jquery.flot.js
jquery.flot.js
tests/jquery.flot.Test.js

FindNearbyItem function had a special mode of handling bars. 
This worked only for hover; in case of cursors most of the time it wasn't able to snap. This happened because it was snapping only if the cursor was inside the bar. There is no need to handle bars different from points.

Cleanup find nearby items

---

dist/jquery.flot.js
jquery.flot.js
tests/jquery.flot.Test.js

The plot area setting should specify how the plot, excluding axes (the grid of the plot) is placed according to it's area. In the case of the webcharts the entire area of the charts, including axes was specified.
Now, the plot offset will be modified accordingly and after this, the axis box position will be aligned with the plot.

Adjust axis and plot margins according to grid margins

---

tests/jquery.flot.canvaswrapper.Test.js
tests/jquery.flot.logaxis.Test.js

On safari, some of our canvaswrapper tests failed caused by pixel ratio. 
More than this, the ticks generated varied in the logaxis test caused by the fact that the number of  ticks was different.
As a side note, if you run the tests multiple times, the getContext() function of html returns null. Apparently, Safari can ran out of total memory to allocate to canvases really fast.... A quick fix to get over this is to reopen the tab that runs the test :(

Fix tests so that they pass on safari 

---

dist/jquery.flot.js
jquery.flot.js

Plot legend colors are selected based on plot index if there's no renderer.
In case we have some plot renderers defined, shift the plot colors so that the legend and plot colors are the same.

Shift plot colors

---

jquery.flot.touchNavigate.js
package-lock.json
tests/jquery.flot.touchNavigate.Test.js

* In case of pinch, the axis to zoom was computed based on the average of the two touches. This could cause the zooming of a certain axis instead of the hole plot
* when the pinch event is ending, update the list of touched axis for the possibility to continue with a pan (lift just one of the fingers and try to pan with the other one)

Touch axis pan fix

---

jquery.flot.navigate.js
jquery.flot.touch.js
jquery.flot.touchNavigate.js
karma.conf.js
package-lock.json
package.json
tests/jquery.flot.navigate-interaction.Test.js
tests/jquery.flot.navigate.Test.js
tests/jquery.flot.touch.Test.js
tests/jquery.flot.touchNavigate.Test.js

* activate plot touch navigation only after tap on plot
* get out of extreme zoom with three fingers pinch by allowing the event propagation to browser
* tests for double tap, zoom and pan

Extreme zoom, highlight plots on tap and several tests

---

.dont-break.json
README.md
circle.yml
package.json

dont-break can be used to check whether the next version of a package will break the dependents.
Because the free plan from CircleCI is limited to 1500 build hours/month, at this point CircleCI/engineering-flot was configured to start a build for PRs only. Eventually we could remove this limitation and let any push to any branch to start a new build.
CircleCI is configured to run in parallel with Travis, but only the Travis build are required to pass in order to merge a PR.

Activating dont-break on CircleCI

---

.dont-break.json
circle.yml

The mainline/released version of dont-break doesn't allow testing indirect dependents.
This change is installing a custom version of dont-break and adds a few indirect dependents to the dont-break list.

Patching dont-break

---

examples/distribution/index.html
jquery.flot.glplotter.js

1. Adding a very basic example for scatter data
2. Adding a switch to force the glplotter plugin when the address of the page contain the gl=true parameter
Now the plugin can be activated in 2 ways:
1. using the gl=true argument in the address, example: http://localhost:2000/examples/distribution/?gl=false This will override the default drawing function for all the point series.
2. passing glshow=true to the data option, example:
```js
var data = [
{
data: [[x1, y1], [x2, y2], [x3, y3]],
points: { show: true, symbol: 'cross', glshow: false },
lines: { show: false }
}
];
plot.setData(data);
plot.setupGrid();
plot.draw();
```

Example gl plotter

---

CHANGELOG.md
dist/es5/jquery.flot.js
jquery.flot.js
tests/jquery.flot.logaxis.Test.js

1. With HTML based labels it was possible to specify in CSS a margin to make sure there is a minimum distance between 2 labels. With SVG this is not possible anymore, so this change is introducing a small fixed margin of 2 * 3 px between 2 consecutive axis tick labels.
2. Fixing the CHANGELOG.md file.

Axis tick label margin

---

API.md
dist/es5/jquery.flot.js
jquery.flot.composeImages.js
jquery.flot.js

Added getPixelRatio function to plot in jquery.flot.
Improved isValidSource function, to check for null and undefined.
Included pixelRatio in image offset computations.
Related PR: https://github.com/ni-kismet/webcharts-legends/pull/77

Img offset with pixel ratio

---

dist/es5/jquery.flot.js
jquery.flot.navigate.js
tests/jquery.flot.navigate.Test.js

The graph navigation was activated only on mouse click. This means that if the user performed a dblclick operation, the graph will autoscale, but the navigation was still not active.
See [issue 174](https://github.com/ni-kismet/engineering-flot/issues/174)

Activate graph navigation on double click

---

CHANGELOG.md
dist/es5/jquery.flot.js
jquery.flot.composeImages.js
tests/jquery.flot.composeImages.Test.js

Downloading a snapshot should not hang on unsupported SVG elements like "use". However, it may still hang on empty SVGs.

Unsupported svg content FireFox

---

dist/es5/jquery.flot.js
jquery.flot.drawSeries.js
package-lock.json

Decimation for lines in case the data is monotonic  needs only the first 4 parameters, but for xy graph, information about Y axis range and height is needed.
Related PR [webcharts 201](https://github.com/ni-kismet/webcharts/pull/201)

Send all the parameters needed for xy line decimation

---

jquery.flot.axislabels.js

The $.extend({
position: 'absolute', ...
results in $.position being stomped.
$.position belongs to jqueryui so anything that uses jqueryui dialogs breaks
so dashboard builder breaks

Fix problem stomping $.position

---

jquery.flot.navigate.js

jQuery may not be defined in this scope. Use '$' instead. This is the way jQWidgets does it.

Axis double-click fix.

---

jquery.flot.legend.js

This fixes an issue when using multiple plots with legends. Before this change, the global options object would refer to the options of the last plot that called init. Because of this, when multiple plots would execute the setupGrid hook, it could insert the legend elements into the wrong container.

Removed global options object in flot.legend

---

source/jquery.flot.absRelTime.js

A recent-ish change, by me, introduced the usage of 'formatToParts' to enable a wider axis formatting set of options. This, however, is not supported on Edge, so Edge has been broken for some time (and there are currently tests that will fail on Edge).
A future update will include updates to the tests that allow us to mark certain tests so that they don't run on Edge, as well as new tests that will validate the new fallback behavior for Edge.

Time formatting fix for edge

---

examples/stacking/index.html
gulpfile.js
karma.conf.js
source/jquery.flot.drawSeries.js
source/jquery.flot.stack.js
tests/jquery.flot-drawSeries.Test.js
tests/jquery.flot.stack.Test.js

This PR fixes the stacking plugin in engineering-flot and allows it to work without being affected by the jquery.flot.flatdata plugin and the 'fillTowards' option. 
In short, the two issues were:
- For stacked bar charts to work, flot needs to draw bars with a top, left, and bottom point. The 'fillTowards' option was being used even if there were bottom points.
- The flatdata plugin manually formats the 'datapoints' objects and prevents the stack plugin from getting the right format (x, y, bottom). Now, the stack plugin will check the format and correct it if necessary.

Fix stacking plugin

---

source/jquery.flot.js

The way the number of definedColors is calculated was incorrect. It assumed no actual color indexes were being used, only strings and null.

Removed definedColors - messes up color assignment

---

source/jquery.flot.time.js

Ran into this in webcharts - when a timeBase wasn't specified it was being calculated as milliseconds

Y Axis default timeBase should match X axis
