ni-kismet/engineering-flot

jquery.canvaswrapper.js
jquery.flot.canvas.js

During the previous changes I incorrectly placed the clearCache function in the jquery.flot.canvas.js file instead of jquery.canvaswrapper.js

Moving the clearCache in the correct file

---

.npmignore
jquery.flot.axislabels.js

These files seams to be the most relevant ones.
The readme, package.json and licence files are automatically included.

Adding .gitignore file

---

jquery.flot.js

finding datamin and datamax is expensive, don't do it if it is not necessary

don't compute datamin and datamax if not autoscaling

---

API.md
examples/fill-types/index.html
jquery.flot.js

implement fillTowards and fix area fill and bar fill broken by the performance fixes

Fill towards

---

jquery.flot.axislabels.js

no more miscalculations.
Also removed canvas and old IE support.
The plan is to switch it to SVG entirely. soon ...

make the axislabels use the axisReserveSpace hook. no more double-draw,

---

API.md
jquery.flot.js

Added small modifications requested by using this function to compute cursors intersection with a plot

Added api for findNearbyItem

---

build.js
dist/jquery.flot.js
package.json

changed the build script to accept arguments. If the "test" is passed as the first argument the script will check that the dist is up to date.

tests that the dist file is up to date

---

dist/jquery.flot.js
examples/axes-autoscaling/index.html
jquery.flot.js
jquery.flot.navigate.js
tests/jquery.flot.Test.js

- add functionality for chart specific autoscale (sliding-window)
- support pan and zoom in all autoscale modes

Fix navigation for autoscale

---

examples/axes-labels/index.html
examples/examples.css
examples/index.html
jquery.flot.axislabels.js
karma.conf.js
tests/jquery.flot.axislabels.Test.js

* Using native DOM functions to measure and add axis labels
* New example that shows a few basic label properties that can be customized with CSS
* Refactoring the axislabels plugin
** Merging the AxisLabel, HtmlAxisLabel and CssTransformAxisLabel objects
* A few tests

Memory leak

---

dist/jquery.flot.js
jquery.flot.axislabels.js
jquery.flot.js
tests/jquery.flot.axislabels.Test.js

Added center left and center height for axes. At the moment, this are used for intensityGraph colorscale position.

Support for reserving space on the left side of the axis

---

dist/jquery.flot.js
jquery.flot.js
tests/jquery.flot.Test.js

when writing fewer samples in the buffer than there are already the buffer needs to be set to the correct length

trim the flot internal buffer 

---

NEWS.md
package-lock.json
package.json

The master is protected so any changes for release needs to follow the same process as any other change.
The release was already published to npm...

New047 release

---

examples/axes-labels/index.html
jquery.flot.axislabels.js

There is no need to recreate the AxisLabel objects anymore.

Recycling the AxisLabel objects

---

jquery.flot.flatdata.js
tests/jquery.flot.flatdata.Test.js

Prevent throwing an exception at edit-time, when data is empty

Add support for empty data

---

build.js
dist/jquery.flot.js
examples/navigate/index.html
jquery.flot.absRelTime.js
jquery.flot.js
jquery.flot.logaxis.js
jquery.flot.navigate.js
jquery.flot.saturated.js
karma.conf.js
tests/jquery.flot-absoluteTimeAxis.Test.js
tests/jquery.flot-drawSeries.Test.js
tests/jquery.flot.Test.js
tests/jquery.flot.largeNumbers.Test.js
tests/jquery.flot.navigate.Test.js

improve the behaviour of the engineering flot when reaching the limits of the double interval

---

dist/jquery.flot.js
jquery.flot.js

It is possible to have axes with no series.

Fix axis with no series

---

API.md
CHANGELOG.md
dist/jquery.flot.js
examples/annotating/index.html
examples/axes-autoscaling/index.html
examples/axes-tickLabels/index.html
examples/basic-options/index.html
examples/distribution/index.html
examples/image/index.html
examples/navigate/index.html
examples/navigateTouch/index.html
examples/percentiles/index.html
examples/selection/index.html
examples/series-errorbars/index.html
examples/stacking/index.html
examples/visitors/index.html
examples/zooming/index.html
jquery.flot.categories.js
jquery.flot.js
jquery.flot.logaxis.js
tests/jquery.flot-absoluteTimeAxis.Test.js
tests/jquery.flot-drawSeries.Test.js
tests/jquery.flot-precision.Test.js
tests/jquery.flot-relativeTimeAxis.Test.js
tests/jquery.flot.Test.js
tests/jquery.flot.logaxis.Test.js
tests/jquery.flot.navigate-interaction.Test.js
tests/jquery.flot.navigate.Test.js
tests/jquery.flot.touch.Test.js
tests/jquery.flot.touchNavigate.Test.js

This PR contains the proposed changed of API for engineering-flot suggested in document https://nitalk.jiveon.com/docs/DOC-448212.
More than this, to keep the consistency between our repos the changelog named here NEWS.md is renamed to CHANGELOG.md

Rename autoscale to autoScale, autoscaleMargin to autoScaleMargin and NEWS.md to CHANGELOG.md

---

API.md
CHANGELOG.md
dist/es5/jquery.flot.js
jquery.flot.composeImages.js
jquery.flot.navigate.js
package-lock.json
package.json
tests/jquery.flot.navigate-interaction.Test.js

The track pad of the Mac is very sensitive and it's firing lots of events for every tiny move of the fingers.
The good part is that the deltaY is reflecting the delta of the pinch distance. These distances are between -1 and 1.
On other OSes the deltaY is always the same: 100 or -100.

Fix mac wheel

---

CHANGELOG.md
dist/es5/jquery.flot.js
jquery.flot.composeImages.js

Made the graph snapshot work on devices with pixel ratio other than 1.

Snapshot pixel ratio

---

CHANGELOG.md

Moved its content to 1.0.3 as it should have been.
https://github.com/ni-kismet/engineering-flot/issues/178

Removed [1.0.4] entry, because it was too soon.

---

dist/es5/jquery.flot.js
jquery.flot.composeImages.js

The snapshot almost works on iPad. It includes now the axes and background SVGs. There is still the problem of supporting legends (SVG with "use" elements).

Added a function to detect mobile Safari browser.

---

dist/es5/jquery.flot.js
jquery.flot.composeImages.js
jquery.flot.legend.js
legend.css

* Fix snapshot for legend
* Add backgroundColor to legend svg instead of div

Legend snapshot

---

API.md
CHANGELOG.md
build.js
dist/es5/jquery.flot.js
examples/interacting/index.html
jquery.flot.hover.js
jquery.flot.js
jquery.flot.navigate.js
jquery.flot.touch.js
karma.conf.js
tests/jquery.flot.hover.Test.js
tests/jquery.flot.navigate.Test.js
tests/jquery.flot.touch.Test.js
touchInteractions.md

* add handler for tap 
* move highlight functions from jquery.flot.js to it's own file
* generate plothover event for tap on point
* generate plothovercleanup event for touch when touch event is not tap

Ephemeral annotation

---

package-lock.json
package.json
tests/jquery.flot.composeImages.Test.js

Using custom jasmine matchers from webcharts-development-settings 1.0.3.

canvasData is now a global function for the tests that use it.

---

dist/es5/jquery.flot.js
jquery.canvaswrapper.js
tests/jquery.flot.canvaswrapper.Test.js

* before, on data update, new tspan element was added inside text element, but they were not removed
* if tspan element should be created, check if there is already an element there and update it's content. Otherwise, create new tspan element

Re-write tspan element content or create one if it does not exist

---

CHANGELOG.md
dist/es5/jquery.flot.js
jquery.flot.hover.js
jquery.flot.navigate.js

* disable by default hoverable option
* on click, if the drag event was not ended, trigger onDragEnd

On click, if was pan, trigger onDragEnd

---

dist/es5/jquery.flot.js
jquery.flot.js

Given the fact that in this for take points[j-ps], if j=0 this will give us undefined

Start looking for points from ps instead of 0

---

.dont-break.json
API.md
CHANGELOG.md
dist/es5/jquery.flot.js
jquery.canvaswrapper.js
jquery.flot.absRelTime.js
jquery.flot.browser.js
jquery.flot.composeImages.js
jquery.flot.js
jquery.flot.logaxis.js
jquery.flot.saturated.js
package-lock.json
tests/jquery.flot.hover.Test.js

* Refactor the floorInBase in one place
* Export getPixelRatio as a static function part of $.plot.browser namespace
* Refactor isSafari and isMobileSafari in one place
* Tests for hover (about 25% feature coverage)
* Temporary removing HeliumUI from dont-break

Tests for hover

---

dist/es5/jquery.flot.js
jquery.flot.navigate.js

Fixing a stupid mistake.
@VirgilChindris please use the new **browser** plugin to refactor the browser specific functions in one place. But please use it wise, not like me :-)

Fix isSafari() function call

---

API.md
CHANGELOG.md
dist/es5/jquery.flot.js
jquery.flot.js

Added a call to overlay.element.onDrawingDone() in drawOverlay function.
Converted onDrawingDone function to event.
Related PR: https://github.com/ni-kismet/webcharts-legends/pull/86

Ready events

---

jquery.flot.browser.js
jquery.flot.composeImages.js

- Very small refactoring of getPixelRatio variable in composeImages.
- Added functions to detect most common web browsers.

Browser detection

---

CHANGELOG.md
dist/es5/jquery.flot.js
examples/examples.css
jquery.flot.composeImages.js
jquery.flot.legend.js
tests/jquery.flot.legend.Test.js

Move background color and background opacity from svg inline style to an inner rectangle.

Fix legend background for snapshot

---

.travis.yml

Travis CI fix for engineering-flot master branch

fix the travis config for CI

---

package-lock.json
package.json

Updating version in package file.

Fix for safari screen capture

---

dist/es5/jquery.flot.js
jquery.flot.js
tests/jquery.flot.Test.js

Do not interpolate outside the range of data provided.
Looks like this repo also has CI issues for chrome

fix interpolation when outside the data range provided

---

.gitignore
gulpfile.js
jquery.canvaswrapper.js
jquery.flot.navigate.js
package-lock.json
package.json

The following changes were necessary for us to proceed with integrating the current version of engineering-flot into the NXG product:
- Do proper es5 transpiling (move to gulp for build process)
- Fix some bugs that were causing existing tests to fail (and there were apparent in-product issues as the result of these bugs)

Changes for 1.x integration into NXG

---

.gitignore
jquery.flot.js
jquery.flot.logaxis.js
tests/jquery.flot.Test.js
tests/jquery.flot.invertedaxis.Test.js

adds support for an "inverted" flag to reverse axis direction in engineering-flot.
There will be an associated check-in in webcharts which enables this in the ni-cartesian-axis element

add support for inverting axis direction

---

docs/API.md

document the inverted property on the flot axis config

Update with inverted property

---

source/jquery.flot.hover.js

We will now attempt to show a hover value when new data is received by re-triggering the plothover event after we clean up the previous one.

Fix for hover value disappearing on data update

---

examples/axes-time/index.html
examples/visitors/index.html
source/jquery.flot.time.js

Also updating some examples to work as expected.

Small fix so we generate better tick deltas.
